import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Homemade_Apple } from "next/font/google";
import { Indie_Flower } from "next/font/google";
import { Gloria_Hallelujah } from "next/font/google";
import { Rock_Salt } from "next/font/google";
import { Handlee } from "next/font/google";
import { Bad_Script } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import { Baskervville } from "next/font/google";
import { Jost } from "next/font/google";
import { Merriweather } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const homemadeApple = Homemade_Apple({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-handwriting",
});

const indieFlower = Indie_Flower({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-indie-flower",
});

const gloriaHallelujah = Gloria_Hallelujah({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-gloria-hallelujah",
});

const rockSalt = Rock_Salt({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-rock-salt",
});

const handlee = Handlee({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-handlee",
});

const badScript = Bad_Script({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bad-script",
});

const playfairDisplay = Playfair_Display({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-playfair-display",
});

const baskervville = Baskervville({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-baskervville",
});

const jost = Jost({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-jost",
});

const merriweather = Merriweather({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-merriweather",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${homemadeApple.variable} 
        ${indieFlower.variable} ${gloriaHallelujah.variable} ${rockSalt.variable} 
        ${handlee.variable} ${badScript.variable} ${playfairDisplay.variable} 
        ${baskervville.variable} ${jost.variable} ${merriweather.variable}
        bg-background text-foreground
        antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
